title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
#logo: 'https://www.detectx.com.au/wp-content/uploads/2020/02/1_rexdjcU2jzkGpA2vBk_udA.png'
#site_favicon: 'https://www.detectx.com.au/wp-content/uploads/2020/02/1_rexdjcU2jzkGpA2vBk_udA.png'
edit_on_github: true
github_docs_folder: fales
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist

plugins:
  - jekyll-toc

